[2024-11-25T15:59:02.780+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:55:24.597952+00:00 [queued]>
[2024-11-25T15:59:02.791+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:55:24.597952+00:00 [queued]>
[2024-11-25T15:59:02.792+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-11-25T15:59:02.814+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-25 15:55:24.597952+00:00
[2024-11-25T15:59:02.842+0000] {standard_task_runner.py:60} INFO - Started process 1640 to run task
[2024-11-25T15:59:02.860+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_project', 'train_model', 'manual__2024-11-25T15:55:24.597952+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/ml_project.py', '--cfg-path', '/tmp/tmpw17hjtqz']
[2024-11-25T15:59:02.863+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask train_model
[2024-11-25T15:59:02.995+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_project.train_model manual__2024-11-25T15:55:24.597952+00:00 [running]> on host e084ca88f62c
[2024-11-25T15:59:03.161+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_project' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T15:55:24.597952+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T15:55:24.597952+00:00'
[2024-11-25T15:59:03.171+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:59:06.764+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/35000 [00:00<?, ? examples/s]
[2024-11-25T15:59:31.805+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:25<00:00, 1397.92 examples/s]
[2024-11-25T15:59:32.103+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:25<00:00, 1381.52 examples/s]
[2024-11-25T15:59:32.152+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/15000 [00:00<?, ? examples/s]
[2024-11-25T15:59:36.731+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:04<00:00, 3276.89 examples/s]
[2024-11-25T15:59:36.839+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:04<00:00, 3202.16 examples/s]
[2024-11-25T15:59:36.842+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:59:38.497+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/pydantic/_internal/_fields.py:149 UserWarning: Field "model_server_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2024-11-25T15:59:38.517+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/pydantic/_internal/_config.py:321 UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
[2024-11-25T15:59:39.217+0000] {logging_mixin.py:188} WARNING - 2024/11/25 15:59:39 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-11-25T15:59:43.049+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/3282 [00:00<?, ?it/s]
[2024-11-25T15:59:46.069+0000] {local_task_job_runner.py:234} INFO - Task exited with return code -9
[2024-11-25T15:59:46.096+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
